define queue model function
leap-api/Leap-Typescript-SDK pull request #5
Opened 2023-05-17 01:25 UTC by PaulLockett

defines the queueModelForTraining function on the ImageLearningService and its associated types.

2023-05-18 02:44 UTC, atbe requested changes

2023-05-18 02:44 UTC, atbe commented on src/core/services/images/LearningService.ts
> +  public async queueModelForTraining(id: string, payload:QueueImageModelForTrainingPayload): Promise<TrainingJobSchema> {
I just pushed a change to the linting workflow to autocheck formatting.

I suggest you install these two plugins (if you're using VSCode):
- https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
- https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint

I just pushed a vscode workspace file that you can open that will automatically pick the extension so your code is formatter automatically as you save/paste so you don't have to think about it.

2023-05-18 02:44 UTC, atbe commented on src/core/services/images/LearningService.ts
>  export class ImageLearningService
Can you add a docstring throughout this file:

- The class
- The methods
- The parameters
- The return objects

2023-05-18 02:44 UTC, atbe commented on src/interfaces/images/LearningServiceInterface.ts
> +  queueModelForTraining: (id: string, payload:QueueImageModelForTrainingPayload) => Promise<TrainingJobSchema>;
Don't use any of the existing models - (if they're from commit `e413ef21f53f559ef6be898397421396790b1396` or earlier), that's legacy code (it'll be removed before release)

Here's an example of a data model class that utilizes the OpenAPI model and is ready to expose to consumers https://github.com/leap-api/Leap-Typescript-SDK/blob/master/src/types/schemas/remix/Remix.ts

For this interface, lets be sure to use newly written models that have proper ties to the OpenAPI models.

2023-05-18 02:44 UTC, atbe commented on src/types/schemas/Model.ts
Let's avoid defining multiple types in one file - for the models related to the `Learning` or `FineTune` features, lets make a subfolder within the `schema` folder [here](https://github.com/leap-api/Leap-Typescript-SDK/tree/master/src/types/schemas) similar to the `remix` feature.

2023-05-18 02:44 UTC, atbe commented on src/types/schemas/Model.ts
> +export type TrainingJobSchema = {
Lets avoid redefining models, and instead extend the OpenAPI generated models

Here's an example of a data model class that utilizes the OpenAPI model and is ready to expose to consumers https://github.com/leap-api/Leap-Typescript-SDK/blob/master/src/types/schemas/remix/Remix.ts

2023-05-18 02:44 UTC, atbe commented on src/types/schemas/QueueImageModelForTrainingPayload.ts
> +export default interface QueueImageModelForTrainingPayload {
Similar comment as above

2023-05-19 23:00 UTC, PaulLockett commented on src/core/services/images/LearningService.ts
> +  public async queueModelForTraining(id: string, payload:QueueImageModelForTrainingPayload): Promise<TrainingJobSchema> {
done

2023-05-19 23:28 UTC, PaulLockett commented on src/core/services/images/LearningService.ts
>  export class ImageLearningService
This has been done

2023-05-19 23:29 UTC, PaulLockett commented on src/interfaces/images/LearningServiceInterface.ts
> +  queueModelForTraining: (id: string, payload:QueueImageModelForTrainingPayload) => Promise<TrainingJobSchema>;
Removed all usages

2023-05-19 23:29 UTC, PaulLockett commented on src/types/schemas/Model.ts
all types are in separate files

2023-05-19 23:29 UTC, PaulLockett commented on src/types/schemas/Model.ts
> +export type TrainingJobSchema = {
Types are now extensions

2023-05-19 23:30 UTC, PaulLockett commented on src/types/schemas/QueueImageModelForTrainingPayload.ts
> +export default interface QueueImageModelForTrainingPayload {
done for his as well

2023-05-22 17:56 UTC, merged